// ════════════════════════════════════════════════════════════════════
// Dados mockados pra modo /demo
// ════════════════════════════════════════════════════════════════════

export const demoClients = [
  {
    id: "demo-client-1",
    slug: "just-burn",
    name: "Just Burn Club",
    legal_name: "Just Burn Club LTDA",
    industry: "fitness",
    plan: "pro",
    status: "active",
    monthly_budget_limit: 15000,
    brand_primary_color: "#FF4D00",
    brand_secondary_color: "#0a0a0a",
    description: "Academia de alta performance em Belo Horizonte",
    logo_url: null,
    website_url: "https://justburn.com.br",
    cnpj: "12.345.678/0001-90",
    requires_approval_above: 1500,
    auto_approve_creatives: false,
    onboarding_completed: true,
  },
  {
    id: "demo-client-2",
    slug: "beat-life",
    name: "Beat Life",
    legal_name: "Beat Life Suplementos LTDA",
    industry: "supplements",
    plan: "pro",
    status: "active",
    monthly_budget_limit: 12000,
    brand_primary_color: "#00C853",
    brand_secondary_color: "#0a0a0a",
    description: "Suplementos premium nacionais",
    logo_url: null,
    website_url: "https://beatlife.com.br",
  },
  {
    id: "demo-client-3",
    slug: "manchester-burger",
    name: "Manchester Burger",
    legal_name: "Manchester Hamburgueria LTDA",
    industry: "food",
    plan: "starter",
    status: "active",
    monthly_budget_limit: 4500,
    brand_primary_color: "#D32F2F",
    brand_secondary_color: "#0a0a0a",
    description: "Hamburgueria artesanal com 8 unidades",
    logo_url: null,
  },
  {
    id: "demo-client-4",
    slug: "flexbyo",
    name: "FlexByo",
    industry: "fashion",
    plan: "premium",
    status: "active",
    monthly_budget_limit: 50000,
    brand_primary_color: "#7C3AED",
    brand_secondary_color: "#0a0a0a",
  },
  {
    id: "demo-client-5",
    slug: "nechio",
    name: "Nechio Cosméticos",
    industry: "beauty",
    plan: "pro",
    status: "onboarding",
    monthly_budget_limit: 8000,
    brand_primary_color: "#EC4899",
  },
  {
    id: "demo-client-6",
    slug: "vortex-tech",
    name: "Vortex Tech",
    industry: "saas",
    plan: "premium",
    status: "active",
    monthly_budget_limit: 30000,
    brand_primary_color: "#06B6D4",
  },
];

export const demoOverview = {
  active_clients: 12,
  total_spend_today: 18435.62,
  total_spend_7d: 124820.4,
  total_spend_30d: 482133.18,
  claude_actions_today: 47,
  pending_approvals: 3,
  active_alerts: 2,
  avg_roas: 3.84,
};

export const demoAlerts = [
  {
    id: "alert-1",
    client_id: "demo-client-1",
    type: "ctr_drop",
    severity: "warning" as const,
    status: "active" as const,
    title: "CTR caiu 42% nas últimas 6h",
    message: "Anúncio 'JB-Conv-003' está performando abaixo da média",
    created_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    client: { name: "Just Burn Club", slug: "just-burn" },
  },
  {
    id: "alert-2",
    client_id: "demo-client-2",
    type: "cpm_high",
    severity: "warning" as const,
    status: "active" as const,
    title: "CPM 67% acima da média histórica",
    message: "Audiência possivelmente saturada — considere expandir lookalike",
    created_at: new Date(Date.now() - 4 * 3600_000).toISOString(),
    client: { name: "Beat Life", slug: "beat-life" },
  },
  {
    id: "alert-3",
    client_id: "demo-client-3",
    type: "budget_low",
    severity: "info" as const,
    status: "active" as const,
    title: "Saldo Meta em 18% do limite mensal",
    message: "Manchester Burger: faltam R$ 820 pra atingir o cap mensal",
    created_at: new Date(Date.now() - 12 * 3600_000).toISOString(),
    client: { name: "Manchester Burger", slug: "manchester-burger" },
  },
];

export const demoApprovals = [
  {
    id: "appr-1",
    client_id: "demo-client-4",
    type: "create_campaign",
    status: "pending" as const,
    title: "Criar campanha 'FlexByo Black Friday Lookalike 1%'",
    description: "Budget mensal estimado: R$ 18.000 — focada em conversão",
    payload: {
      objective: "OUTCOME_SALES",
      daily_budget: 600,
      audience: "Lookalike 1% Compradores 90d",
      placements: ["facebook_feed", "instagram_feed", "instagram_reels"],
    },
    estimated_impact: {
      monthly_budget: 18000,
      audience_size: 850000,
      objective: "OUTCOME_SALES",
    },
    claude_reasoning:
      "Cliente solicitou expandir antes da Black Friday. Lookalike 1% historicamente performa 2.3x melhor que interesse amplo.",
    created_at: new Date(Date.now() - 30 * 60_000).toISOString(),
    expires_at: new Date(Date.now() + 23 * 3600_000).toISOString(),
    client: { name: "FlexByo", slug: "flexbyo" },
  },
  {
    id: "appr-2",
    client_id: "demo-client-1",
    type: "creative_launch",
    status: "pending" as const,
    title: "Lançar 3 variações de criativo Just Burn",
    description: "Variações testando hooks emocionais diferentes (transformação, comunidade, performance)",
    payload: { ad_count: 3, ad_set_id: "adset_jb_456" },
    estimated_impact: {
      audience_size: 320000,
      platforms: ["instagram", "facebook"],
    },
    claude_reasoning:
      "Criativos atuais com frequency >4 — perfeito momento pra refresh visual mantendo audiência.",
    created_at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    expires_at: new Date(Date.now() + 22 * 3600_000).toISOString(),
    client: { name: "Just Burn Club", slug: "just-burn" },
  },
  {
    id: "appr-3",
    client_id: "demo-client-2",
    type: "budget_change",
    status: "pending" as const,
    title: "Aumentar daily budget Beat Life Quaresma +35%",
    description: "Camp 'BL-Hipertrofia-2025' está com ROAS 5.8x — escalar agressivo",
    payload: { campaign_id: "camp_bl_789", new_daily_budget: 540 },
    estimated_impact: { monthly_budget: 16200 },
    claude_reasoning:
      "ROAS muito acima da meta (3x). Aumentar 35% mantém margem segura e aproveita janela de alta intenção.",
    created_at: new Date(Date.now() - 6 * 3600_000).toISOString(),
    expires_at: new Date(Date.now() + 18 * 3600_000).toISOString(),
    client: { name: "Beat Life", slug: "beat-life" },
  },
];

export const demoClaudeActions = [
  {
    id: "act-1",
    tool_name: "create_creative",
    status: "success",
    duration_ms: 1842,
    reasoning: "Criando 3 variações com hooks emocionais conforme solicitado",
    created_at: new Date(Date.now() - 5 * 60_000).toISOString(),
    client: { name: "Just Burn Club" },
  },
  {
    id: "act-2",
    tool_name: "pause_ad",
    status: "success",
    duration_ms: 892,
    reasoning: "Frequency 5.2 — fadiga detectada",
    created_at: new Date(Date.now() - 14 * 60_000).toISOString(),
    client: { name: "Beat Life" },
  },
  {
    id: "act-3",
    tool_name: "get_performance",
    status: "success",
    duration_ms: 412,
    reasoning: "Análise semanal solicitada",
    created_at: new Date(Date.now() - 22 * 60_000).toISOString(),
    client: { name: "FlexByo" },
  },
  {
    id: "act-4",
    tool_name: "update_campaign",
    status: "success",
    duration_ms: 1124,
    reasoning: "Aumento aprovado de R$400 → R$540 daily",
    created_at: new Date(Date.now() - 38 * 60_000).toISOString(),
    client: { name: "Beat Life" },
  },
  {
    id: "act-5",
    tool_name: "create_alert",
    status: "success",
    duration_ms: 234,
    reasoning: "CTR caiu 42% — gerando alerta pra equipe",
    created_at: new Date(Date.now() - 52 * 60_000).toISOString(),
    client: { name: "Just Burn Club" },
  },
  {
    id: "act-6",
    tool_name: "sync_meta_data",
    status: "success",
    duration_ms: 4231,
    reasoning: "Sync agendado a cada 15min",
    created_at: new Date(Date.now() - 70 * 60_000).toISOString(),
    client: { name: "Manchester Burger" },
  },
  {
    id: "act-7",
    tool_name: "generate_report",
    status: "success",
    duration_ms: 3120,
    reasoning: "Relatório semanal gerado e enviado",
    created_at: new Date(Date.now() - 90 * 60_000).toISOString(),
    client: { name: "Vortex Tech" },
  },
  {
    id: "act-8",
    tool_name: "duplicate_creative",
    status: "failed",
    duration_ms: 5012,
    reasoning: "Variação A/B com headline alternativo",
    created_at: new Date(Date.now() - 124 * 60_000).toISOString(),
    client: { name: "Nechio Cosméticos" },
  },
];

export const demoAuditLogs = [
  {
    id: "log-1",
    actor_type: "claude",
    actor_email: null,
    action: "campaign.created",
    resource_type: "campaign",
    created_at: new Date(Date.now() - 5 * 60_000).toISOString(),
    client: { name: "Just Burn Club" },
  },
  {
    id: "log-2",
    actor_type: "user",
    actor_email: "kendy@agenciabase.tech",
    action: "approval.approved",
    resource_type: "approval",
    created_at: new Date(Date.now() - 18 * 60_000).toISOString(),
    client: { name: "Beat Life" },
  },
  {
    id: "log-3",
    actor_type: "claude",
    actor_email: null,
    action: "ad.paused",
    resource_type: "ad",
    created_at: new Date(Date.now() - 32 * 60_000).toISOString(),
    client: { name: "Beat Life" },
  },
  {
    id: "log-4",
    actor_type: "system",
    actor_email: null,
    action: "alert.auto_resolved",
    resource_type: "alert",
    created_at: new Date(Date.now() - 47 * 60_000).toISOString(),
    client: { name: "FlexByo" },
  },
  {
    id: "log-5",
    actor_type: "user",
    actor_email: "marina@flexbyo.com.br",
    action: "creative.approved",
    resource_type: "ad",
    created_at: new Date(Date.now() - 65 * 60_000).toISOString(),
    client: { name: "FlexByo" },
  },
  {
    id: "log-6",
    actor_type: "cron",
    actor_email: null,
    action: "meta.sync_run",
    resource_type: "system",
    created_at: new Date(Date.now() - 75 * 60_000).toISOString(),
    client: null,
  },
];

export const demoPerformanceJB = {
  spend: 8412.36,
  conversion_value: 35332.41,
  roas: 4.2,
  ctr: 2.74,
  cpc: 1.34,
  cpm: 36.67,
  cpa: 28.4,
  frequency: 1.45,
  impressions: 245820,
  reach: 168432,
  clicks: 6738,
  conversions: 296,
};

export const demoChartData = (() => {
  const days = 7;
  const data = [];
  const baseSpend = 1100;
  const baseRevenue = 4500;
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const date = d.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" });
    const variance = 0.6 + Math.random() * 0.8;
    data.push({
      date,
      spend: Math.round(baseSpend * variance),
      revenue: Math.round(baseRevenue * variance),
    });
  }
  return data;
})();

export const demoAds = [
  {
    id: "ad-1",
    name: "JB-Conv-001",
    status: "active",
    headline: "Transforme seu corpo em 12 semanas",
    body: "Plano completo que mais que dobrou os resultados de 2.348 alunos. Garantia ou seu dinheiro de volta.",
    cta_type: "SIGN_UP",
    image_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=800&fit=crop",
    thumbnail_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    approved_by_client: true,
  },
  {
    id: "ad-2",
    name: "JB-Conv-002",
    status: "active",
    headline: "Adeus academia chata. Olá Just Burn.",
    body: "Treinos curtos, intensos e divertidos. Comunidade que te puxa quando você quer desistir.",
    cta_type: "LEARN_MORE",
    image_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=800&fit=crop",
    thumbnail_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    approved_by_client: true,
  },
  {
    id: "ad-3",
    name: "JB-Conv-003-VAR-A",
    status: "pending_approval",
    headline: "Você merece se sentir foda",
    body: "Não é só sobre estética — é sobre ser inquebrável. Mente e corpo treinados juntos.",
    cta_type: "SIGN_UP",
    image_url: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&h=800&fit=crop",
    thumbnail_url: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400",
    approved_by_client: false,
  },
  {
    id: "ad-4",
    name: "JB-Conv-003-VAR-B",
    status: "pending_approval",
    headline: "Apenas 12 semanas pra virar a chave",
    body: "Acompanhamento individual + treinos online + comunidade exclusiva. Mais de 5.000 transformações.",
    cta_type: "GET_OFFER",
    image_url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop",
    thumbnail_url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
    approved_by_client: false,
  },
  {
    id: "ad-5",
    name: "JB-Conv-003-VAR-C",
    status: "pending_approval",
    headline: "Treine onde for. Conquiste o impossível.",
    body: "App + treinos + comunidade. Uma turma nova começa toda semana — sua vez é agora.",
    cta_type: "DOWNLOAD",
    image_url: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&h=800&fit=crop",
    thumbnail_url: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400",
    approved_by_client: false,
  },
  {
    id: "ad-6",
    name: "JB-Conv-Old-001",
    status: "paused",
    headline: "Resultados em 60 dias garantidos",
    body: "Plano antigo pausado por fadiga (frequency 5.2)",
    cta_type: "LEARN_MORE",
    image_url: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&h=800&fit=crop",
    thumbnail_url: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=400",
    approved_by_client: true,
  },
];

export const demoCampaignBreakdown = [
  { name: "JB-Conversão-Mulheres-25-45-BH", spend: 4820.5, revenue: 22340.18 },
  { name: "JB-Lookalike-1%-Compradores-90d", spend: 2340.18, revenue: 9821.5 },
  { name: "JB-Retargeting-Site-30d", spend: 1180.4, revenue: 5430.2 },
  { name: "JB-Awareness-Frio-Geral", spend: 312.0, revenue: 480.0 },
];

export const demoMessages = [
  {
    id: "m-1",
    sender_id: "demo-admin",
    sender_role: "admin" as const,
    content: "Boa tarde Marina! Coloquei 3 variações novas pra rodar essa semana — passa lá no painel pra aprovar quando puder.",
    created_at: new Date(Date.now() - 8 * 3600_000).toISOString(),
    sender: { full_name: "Kendy (Agência BASE)", avatar_url: null },
  },
  {
    id: "m-2",
    sender_id: "demo-client-user",
    sender_role: "client_admin" as const,
    content: "Top, Kendy! Acabei de aprovar as 3. Curti muito a variação A — bem na pegada da marca. ROAS bom essa semana?",
    created_at: new Date(Date.now() - 7 * 3600_000).toISOString(),
    sender: { full_name: "Marina (FlexByo)", avatar_url: null },
  },
  {
    id: "m-3",
    sender_id: "demo-admin",
    sender_role: "admin" as const,
    content: "Tá em 4.2x essa semana 🚀 Tem oportunidade de escalar o lookalike +35% — Claude já mandou pedido de aprovação na sua fila.",
    created_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    sender: { full_name: "Kendy (Agência BASE)", avatar_url: null },
  },
  {
    id: "m-4",
    sender_id: "demo-client-user",
    sender_role: "client_admin" as const,
    content: "Aprovado! Pode mandar ver. E o relatório semanal sai sexta?",
    created_at: new Date(Date.now() - 30 * 60_000).toISOString(),
    sender: { full_name: "Marina (FlexByo)", avatar_url: null },
  },
];

export const demoHistorico = [
  { action_type: "create_campaign", reasoning: "Nova campanha 'Black Friday Lookalike' criada e aguardando início", at: 30 * 60_000 },
  { action_type: "create_creative", reasoning: "3 variações novas geradas pra teste A/B/C", at: 5 * 3600_000 },
  { action_type: "pause_ad", reasoning: "Anúncio JB-Conv-Old-001 pausado por fadiga (frequency 5.2)", at: 8 * 3600_000 },
  { action_type: "budget_change", reasoning: "Aumento de R$ 400 → R$ 540 daily budget aprovado", at: 14 * 3600_000 },
  { action_type: "generate_report", reasoning: "Relatório semanal gerado e disponibilizado", at: 24 * 3600_000 },
  { action_type: "resume_campaign", reasoning: "Campanha 'Quaresma 2025' reativada após otimização", at: 48 * 3600_000 },
  { action_type: "create_creative", reasoning: "Variação com hook emocional baseada em depoimento real", at: 72 * 3600_000 },
  { action_type: "sync_meta_data", reasoning: "Sincronização agendada", at: 96 * 3600_000 },
].map((h, i) => ({
  id: `hist-${i}`,
  ...h,
  created_at: new Date(Date.now() - h.at).toISOString(),
}));
